Repository CMU-313/fall23-nodebb-tech-tartans, pull requests merged in 2023-10, with the labels that each got.

#32 Implements "resolve" frontend feature and backend logic
  package 2.json
  public/openapi/write.yaml
  public/openapi/write/topics/tid/resolve.yaml
  public/src/client/category/tools.js
  public/src/client/topic/events.js
  public/src/client/topic/threadTools.js
  src/api/topics.js
  src/controllers/write/topics.js
  src/routes/write/topics.js
  src/topics/index.js
  src/topics/tools.js
  themes/nodebb-theme-persona/less/categories.less
  themes/nodebb-theme-persona/templates/partials/category/tools.tpl
  themes/nodebb-theme-persona/templates/partials/topic/topic-menu-list.tpl
  themes/nodebb-theme-persona/templates/partials/topics_list.tpl
  themes/nodebb-theme-persona/templates/topic.tpl
Labels: bug, implementation

#35 Fixed dropdown list not showing 'Unresolve Topic' field
  public/src/client/category/tools.js
Labels: implementation

#40 Make friend filter button clickable and resolve test failures during merge
  public/language/en-GB/category.json
  public/src/client/account/categories.js
  public/src/client/category.js
  public/src/client/header/unread.js
  src/categories/index.js
  src/categories/watch.js
  src/controllers/accounts/categories.js
  themes/nodebb-theme-persona/templates/account/categories.tpl
  themes/nodebb-theme-persona/templates/partials/category/watch.tpl
Labels: bug, enhancement
